[program:centrifugo]
command = centrifugo -c /var/pheme/centrifugo/config.json
directory = /var/pheme/centrifugo
user = pheme
priority = 700
numprocs = 1
autostart = true
autorestart = true
redirect_stderr = true

# Logfiles
stdout_logfile = /var/pheme/logs/service_centrifugo.log
stdout_logfile_maxbytes = 5MB
stdout_logfile_backups = 5
