[program:sftpgo]
command = sftpgo --config-dir=/var/pheme/sftpgo serve -l ""
directory = /var/pheme/sftpgo
user = pheme
priority = 700
numprocs = 1
autostart = true
autorestart = true
redirect_stderr = true

stopasgroup = true
killasgroup = true

# Logfiles
stdout_logfile = /var/pheme/logs/service_sftpgo.log
stdout_logfile_maxbytes = 5MB
stdout_logfile_backups = 5
