#!/usr/bin/env bash

##############################################################################
# setup_pheme_install
##############################################################################

# Clone and checkout Pheme stable branch
su pheme <<EOF
    git clone https://github.com/ashd0wn/Pheme.git /var/pheme/www
    git -C /var/pheme/www checkout -f ${set_pheme_version}-org
    composer --working-dir=/var/pheme/www install --no-dev --no-ansi --no-interaction
EOF

# Directories 0755
find /var/pheme/www -type d -exec chmod 755 {} \;

# Files 0644
find /var/pheme/www -type f -exec chmod 644 {} \;

# Populate env.ini
echo "
;
; Pheme Environment Settings
;
; This file is automatically generated by Pheme.
;

[configuration]
application_env = production
MYSQL_HOST = localhost
MYSQL_PORT = 3306
MYSQL_USER = phemeMySQLUsername
MYSQL_DB = phemeMySQLDatabase
MYSQL_PASSWORD = phemeMySQLPassword
" >> /var/pheme/www/env.ini

# Inject DB credentials
sed -i "s/phemeMySQLDatabase/$set_pheme_database/g" /var/pheme/www/env.ini
sed -i "s/phemeMySQLUsername/$set_pheme_username/g" /var/pheme/www/env.ini
sed -i "s/phemeMySQLPassword/$set_pheme_password/g" /var/pheme/www/env.ini

# Secure env.ini
chmod 0640 /var/pheme/www/env.ini
chown pheme.pheme /var/pheme/www/env.ini

# Migrate DB
supervisorctl restart redis
supervisorctl restart mariadb
php /var/pheme/www/bin/console pheme:setup:migrate
supervisorctl stop mariadb

# Build frontend
echo -en "\n- Build Pheme\n"
source pheme/build.sh || { echo "Error sourcing build.sh"; exit 1; }

# Set ulimit
echo -en "\n- Set ulimit\n"
source pheme/ulimit.sh || { echo "Error sourcing ulimit.sh"; exit 1; }

# Configure logs
echo -en "\n- Set Pheme Logs\n"
source pheme/logs.sh || { echo "Error sourcing logs.sh"; exit 1; }
