#!/usr/bin/env bash

##############################################################################
# setup_pheme_install
##############################################################################

# Clone Pheme Stable Branch.
#
# To make sure, that this installer will always work, this is not Phemes default Stable branch.
# Its the same codebase as the Original.
#
# But i will make sure, that anything is working before updateing to latest stable version.
# If you want, you can change it to its original. But you shouldnt ask for help in this case.

# Get required files
if [ "$pheme_git_version" = "stable" ]; then
    su pheme <<EOF
    git clone https://github.com/ashd0wn/Pheme.git /var/pheme/www
    git -C /var/pheme/www checkout -f ${set_pheme_version}-org
    composer --working-dir=/var/pheme/www install --no-dev --no-ansi --no-interaction
EOF
elif [ "$pheme_git_version" = "rolling" ]; then
    su pheme <<EOF
    git clone https://github.com/ashd0wn/Pheme.git /var/pheme/www
    git -C /var/pheme/www checkout -f rolling
    composer --working-dir=/var/pheme/www install --no-dev --no-ansi --no-interaction
EOF
else
    su pheme <<EOF
    git clone https://github.com/ashd0wn/Pheme.git /var/pheme/www
    git -C /var/pheme/www checkout -f ${set_pheme_version}-scy
    composer --working-dir=/var/pheme/www install --no-dev --no-ansi --no-interaction
EOF
fi

# Directories 0755
find /var/pheme/www -type d -exec chmod 755 {} \;

# Files 0644
find /var/pheme/www -type f -exec chmod 644 {} \;

# Popluate env.ini
echo "
;
; Pheme Environment Settings
;
; This file is automatically generated by Pheme.
;

[configuration]
application_env = production
MYSQL_HOST = localhost
MYSQL_PORT = 3306
MYSQL_USER = phemeMySQLUsername
MYSQL_DB = phemeMySQLDatabase
MYSQL_PASSWORD = phemeMySQLPassword
" >>/var/pheme/www/env.ini

# Set right DB Password
sed -i "s/phemeMySQLDatabase/$set_pheme_database/g" /var/pheme/www/env.ini
sed -i "s/phemeMySQLUsername/$set_pheme_username/g" /var/pheme/www/env.ini
sed -i "s/phemeMySQLPassword/$set_pheme_password/g" /var/pheme/www/env.ini

# CHMOD & CHOWN env.ini
chmod 0640 /var/pheme/www/env.ini
chown pheme.pheme /var/pheme/www/env.ini

# Migrate DB
supervisorctl restart redis
supervisorctl restart mariadb
php /var/pheme/www/bin/console pheme:setup:migrate
supervisorctl stop mariadb

# Build
echo -en "\n- Build Pheme\n"
source pheme/build.sh || { echo "Error sourcing build.sh"; exit 1; }

# /etc/security/limits.conf
echo -en "\n- Set ulimit\n"
source pheme/ulimit.sh || { echo "Error sourcing ulimit.sh"; exit 1; }

# Logs
echo -en "\n- Set Pheme Logs\n"
source pheme/logs.sh || { echo "Error sourcing logs.sh"; exit 1; }
